---
- name: "Compactor: Install thanos compact systemd file"
  template:
    src: thanos-compactor.j2
    dest: /etc/systemd/system/thanos-compactor.service
  tags:
    - compactor
    - configuration
  notify: 
    - reload systemd daemon
    - restart thanos-compactor

- name: "Compactor: Add defaults file"
  template:
    src: thanos-compactor-defaults.j2
    dest: /etc/default/thanos-compactor
  tags:
    - compactor
    - configuration
  notify: restart thanos-compactor

- name: "Compactor: generate configuration file"
  template:
    src: thanos-s3-config.j2
    dest: "{{ thanos_compactor_config_file }}"
  tags:
    - compactor
    - configuration
  notify: restart thanos-compactor

- name: "Compactor: Ensure thanos-compactor is started"
  service:
    name: thanos-compactor
    enabled: true
    daemon-reload: true
    state: started
  tags:
    - compactor
    - startup
