---
- name: "Compactor: Install thanos compact systemd file"
  template:
    src: thanos-compactor.j2
    dest: /etc/systemd/system/thanos-compactor.service
  register: compact_systemd
  notify: restart thanos-compactor

- name: "Compactor: Reload systemd if thanos compact changed"
  systemd:
    daemon_reload: yes

- name: "Compactor: Add defaults file"
  template:
    src: thanos-compactor-defaults.j2
    dest: /etc/default/thanos-compactor
  notify: restart thanos-compact

- name: "Compactor: generate configuration file"
  template:
    src: thanos-s3-config.j2
    dest: "{{ thanos_compactor_config_file }}"
  notify: restart thanos-compactor

- name: "Compactor: Ensure thanos-compactor is started"
  service:
    name: thanos-compactor
    enabled: yes
    state: started
