---
- name: "Query: Install thanos query systemd file"
  template:
    src: thanos-query.j2
    dest: /etc/systemd/system/thanos-query.service
  register: query_systemd
  notify: restart thanos-query

- name: "Query: Reload systemd if thanos query changed"
  systemd:
    daemon_reload: true

- name: "Query: Add defaults file"
  template:
    src: thanos-query-defaults.j2
    dest: /etc/default/thanos-query
  notify: restart thanos-query

- name: "Query: Ensure thanos-query is started"
  service:
    name: thanos-query
    enabled: true
    state: started
