---

- name: reload systemd daemon
  systemd:
    daemon-reload: true

- name: restart thanos-sidecar
  service:
    name: thanos-sidecar
    state: restarted

- name: restart thanos-query
  service:
    name: thanos-query
    state: restarted

- name: restart thanos-compactor
  service:
    name: thanos-compactor
    state: restarted

- name: restart thanos-store
  service:
    name: thanos-store
    state: restarted
