---

- name: restart thanos-sidecar
  service:
    name: thanos-sidecar
    state: restarted

- name: restart thanos-query
  service:
    name: thanos-query
    state: restarted

- name: restart thanos-compact
  service:
    name: thanos-compactor
    state: restarted

- name: restart thanos-compact timer
  systemd:
    name: thanos-compactor.timer
    daemon-reload: yes
    state: restarted
    enabled: true

- name: restart thanos-store
  service:
    name: thanos-store
    state: restarted
