---

- name: restart thanos-sidecar
  service:
    name: thanos-sidecar
    state: restarted
  when: thanos_sidecar_enabled is defined and thanos_sidecar_enabled == True

- name: restart thanos-query
  service:
    name: thanos-query
    state: restarted
  when: thanos_query_enabled is defined and thanos_query_enabled == True

- name: restart thanos-compact
  service:
    name: thanos-compactor
    state: restarted
  when: thanos_compactor_enabled is defined and thanos_query_enabled == True

- name: restart thanos-compact timer
  systemd:
    name: thanos-compactor.timer
    daemon-reload: yes
    state: restarted
    enabled: true

